nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.5.1.cjs

# Required to prevent "Error: Cannot find module '@storybook/react-webpack5/preset'"
# packageExtensions:
#   "@storybook/core-common@*":
#     dependencies:
#       "@babel/core": "*"
#       "@storybook/angular": "*"
#       "@storybook/react-webpack5": "*"
#       "react": "*"
#       "react-dom": "*"
