# Required by vite:dts when running in Netlify
nodeLinker: node-modules

# Required to overcome Storybook issue and SCSS imports from hoisted packages
nmHoistingLimits: workspaces

# packageExtensions:
#   "@storybook/core-common@*":
#     dependencies:
#       "@storybook/react-webpack5": "^7.0.6"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
