nodeLinker: node-modules

nmHoistingLimits: workspaces

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-webpack5": "^7.0.4"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
