# Required by Netlify
nmHoistingLimits: workspaces

# Required to overcome Storybook issue and SCSS imports from hoisted packages
nodeLinker: node-modules

# Supports `yarn upgrade-interactive`
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
