# Required by Netlify
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.5.1.cjs

# Required to prevent "Error: Cannot find module '@storybook/react-webpack5/preset'"
packageExtensions:
  "@storybook/core-common@*":
      dependencies:
        "@storybook/react-webpack5": "7.0.3"