import { NgModule } from '@angular/core'

import {
	AlluvialChartComponent,
	AreaChartComponent,
	BaseChartComponent,
	BoxplotChartComponent,
	BubbleChartComponent,
	BulletChartComponent,
	ChoroplethChartComponent,
	CirclePackChartComponent,
	ComboChartComponent,
	DonutChartComponent,
	ExperimentalChoroplethChartComponent,
	GaugeChartComponent,
	GroupedBarChartComponent,
	HeatmapChartComponent,
	HistogramChartComponent,
	LineChartComponent,
	LollipopChartComponent,
	MeterChartComponent,
	PieChartComponent,
	RadarChartComponent,
	ScatterChartComponent,
	SimpleBarChartComponent,
	StackedAreaChartComponent,
	StackedBarChartComponent,
	TreeChartComponent,
	TreemapChartComponent,
	WordCloudChartComponent
} from './index'

@NgModule({
	declarations: [],
	imports: [
		AlluvialChartComponent,
		AreaChartComponent,
		BaseChartComponent,
		BoxplotChartComponent,
		BubbleChartComponent,
		BulletChartComponent,
		ChoroplethChartComponent,
		CirclePackChartComponent,
		ComboChartComponent,
		DonutChartComponent,
		ExperimentalChoroplethChartComponent,
		GaugeChartComponent,
		GroupedBarChartComponent,
		HeatmapChartComponent,
		HistogramChartComponent,
		LineChartComponent,
		LollipopChartComponent,
		MeterChartComponent,
		PieChartComponent,
		RadarChartComponent,
		ScatterChartComponent,
		SimpleBarChartComponent,
		StackedAreaChartComponent,
		StackedBarChartComponent,
		TreeChartComponent,
		TreemapChartComponent,
		WordCloudChartComponent
	],
	exports: [
		AlluvialChartComponent,
		AreaChartComponent,
		BaseChartComponent,
		BoxplotChartComponent,
		BubbleChartComponent,
		BulletChartComponent,
		ChoroplethChartComponent,
		CirclePackChartComponent,
		ComboChartComponent,
		DonutChartComponent,
		/**
		 * @deprecated Use `ChoroplethChartComponent` instead.
		 */
		ExperimentalChoroplethChartComponent,
		GaugeChartComponent,
		GroupedBarChartComponent,
		HeatmapChartComponent,
		HistogramChartComponent,
		LineChartComponent,
		LollipopChartComponent,
		MeterChartComponent,
		PieChartComponent,
		RadarChartComponent,
		ScatterChartComponent,
		SimpleBarChartComponent,
		StackedAreaChartComponent,
		StackedBarChartComponent,
		TreeChartComponent,
		TreemapChartComponent,
		WordCloudChartComponent
	]
})
export class ChartsModule {}
