import { NgModule } from '@angular/core'
import { CommonModule } from '@angular/common'

import {
	AlluvialChartComponent,
	AreaChartComponent,
	BaseChartComponent,
	BoxplotChartComponent,
	BubbleChartComponent,
	BulletChartComponent,
	CirclePackChartComponent,
	ComboChartComponent,
	DonutChartComponent,
	ExperimentalChoroplethChartComponent,
	GaugeChartComponent,
	GroupedBarChartComponent,
	HeatmapChartComponent,
	HistogramChartComponent,
	LineChartComponent,
	LollipopChartComponent,
	MeterChartComponent,
	PieChartComponent,
	RadarChartComponent,
	ScatterChartComponent,
	SimpleBarChartComponent,
	StackedAreaChartComponent,
	StackedBarChartComponent,
	TreeChartComponent,
	TreemapChartComponent,
	WordCloudChartComponent
} from './index'

@NgModule({
	declarations: [
		BaseChartComponent,
		AlluvialChartComponent,
		AreaChartComponent,
		StackedAreaChartComponent,
		SimpleBarChartComponent,
		GroupedBarChartComponent,
		StackedBarChartComponent,
		BoxplotChartComponent,
		BubbleChartComponent,
		BulletChartComponent,
		DonutChartComponent,
		ExperimentalChoroplethChartComponent,
		GaugeChartComponent,
		HeatmapChartComponent,
		HistogramChartComponent,
		LineChartComponent,
		LollipopChartComponent,
		PieChartComponent,
		ScatterChartComponent,
		MeterChartComponent,
		RadarChartComponent,
		ComboChartComponent,
		TreeChartComponent,
		TreemapChartComponent,
		CirclePackChartComponent,
		WordCloudChartComponent
	],
	imports: [CommonModule],
	exports: [
		BaseChartComponent,
		AlluvialChartComponent,
		AreaChartComponent,
		StackedAreaChartComponent,
		SimpleBarChartComponent,
		GroupedBarChartComponent,
		StackedBarChartComponent,
		BoxplotChartComponent,
		BubbleChartComponent,
		BulletChartComponent,
		DonutChartComponent,
		ExperimentalChoroplethChartComponent,
		GaugeChartComponent,
		HeatmapChartComponent,
		HistogramChartComponent,
		LineChartComponent,
		LollipopChartComponent,
		PieChartComponent,
		ScatterChartComponent,
		MeterChartComponent,
		RadarChartComponent,
		ComboChartComponent,
		TreeChartComponent,
		TreemapChartComponent,
		CirclePackChartComponent,
		WordCloudChartComponent
	]
})
export class ChartsModule {}
