import { NgModule } from '@angular/core'
import { CommonModule } from '@angular/common'

import {
	AlluvialChart,
	AreaChart,
	BaseChart,
	BoxplotChart,
	BubbleChart,
	BulletChart,
	CirclePackChart,
	ComboChart,
	DonutChart,
	GaugeChart,
	GroupedBarChart,
	HeatmapChart,
	HistogramChart,
	LineChart,
	LollipopChart,
	MeterChart,
	PieChart,
	RadarChart,
	ScatterChart,
	SimpleBarChart,
	StackedAreaChart,
	StackedBarChart,
	TreeChart,
	TreemapChart,
	WordCloudChart
} from './index'

@NgModule({
	imports: [
		CommonModule,
		BaseChart,
		AlluvialChart,
		AreaChart,
		StackedAreaChart,
		SimpleBarChart,
		GroupedBarChart,
		StackedBarChart,
		BoxplotChart,
		BubbleChart,
		BulletChart,
		DonutChart,
		GaugeChart,
		HeatmapChart,
		HistogramChart,
		LineChart,
		LollipopChart,
		PieChart,
		ScatterChart,
		MeterChart,
		RadarChart,
		ComboChart,
		TreeChart,
		TreemapChart,
		CirclePackChart,
		WordCloudChart
	],
	exports: [
		BaseChart,
		AlluvialChart,
		AreaChart,
		StackedAreaChart,
		SimpleBarChart,
		GroupedBarChart,
		StackedBarChart,
		BoxplotChart,
		BubbleChart,
		BulletChart,
		DonutChart,
		GaugeChart,
		HeatmapChart,
		HistogramChart,
		LineChart,
		LollipopChart,
		PieChart,
		ScatterChart,
		MeterChart,
		RadarChart,
		ComboChart,
		TreeChart,
		TreemapChart,
		CirclePackChart,
		WordCloudChart
	]
})
export class ChartsModule {}
