name: Bug report 🐛
description: Something isn't working as expected
title: '[Bug]: '
labels: [bug 🐛]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: checkboxes
    id: packages
    attributes:
      label: Relevant package(s)
      options:
        - label: '@carbon/charts'
        - label: '@carbon/charts-svelte'
        - label: '@carbon/charts-react'
        - label: '@carbon/charts-angular'
        - label: '@carbon/charts-vue'
        - label: 'Documentation website'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Carbon Charts Version
      placeholder: 1.16.1
    validations:
      required: true
  - type: dropdown
    id: bundler
    attributes:
      label: Which bundler are you using?
      options:
        - None (UMD)
        - Esbuild
        - FuseBox
        - Parcel
        - Rollup
        - Snowpack
        - Webpack
        - Vite
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened and what did you expect to happen?
      description:
        Include steps to reproduce and environmental information such as your framework version (eg.
        Angular 18.0.1)
    validations:
      required: true
  - type: textarea
    id: data-options
    attributes:
      label: Chart data and options (automatically formatted so no need for backticks)
      description: Please provide both
      render: js
  - type: textarea
    id: logs
    attributes:
      label: JavaScript console or build output (if relevant)
      description: Automatically formatted so no need for backticks
      render: shell
  - type: input
    id: repro
    attributes:
      label: StackBlitz repro
      description: Get started with StackBlitz examples at https://charts.carbondesignsystem.com
      placeholder: https://www.stackblitz.com/...
  - type: input
    id: name
    attributes:
      label: IBM Application/Team (if relevant)
  - type: dropdown
    id: priority
    attributes:
      label: What priority level would this be in your opinion?
      options:
        - P0 (Critical)
        - P1 (High)
        - P2 (Medium)
        - P3 (Low)
        - P4 (Trivial)
    validations:
      required: true
