#!/usr/bin/env sh

# Keep this POSIX-compliant so Windows workstations can contribute to the project
set -e

# Lint each package (supress Node deprecation warnings)
if ! NODE_OPTIONS="--no-warnings" npx lerna run lint; then
    echo "Error: Linting failed. Please fix the lint errors and try committing again."
    exit 1
fi

# Check to see if yarn.lock was modified since last commit and add it, if it was
if [ -n "$(git ls-files -m | grep yarn.lock)" ]; then
    git add yarn.lock
    git commit -m "chore(monorepo): update yarn.lock" --no-verify
fi

# Run prettier on all packages (supress Node deprecation warnings)
NODE_OPTIONS="--no-warnings" npx lerna run format

#exit 1 # stops push from running, good for testing
